version: '3.8'

services:
  angular-app:
    image: prasadwalujkar05/angu:latest # Use the pre-built image
    ports:
      - "4200:80"
    networks:
      - app-network

  springboot-app:
    image: prasadwalujkar05/shopping:latest # Use the pre-built image
    ports:
      - "9090:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/timetracker
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysqldb
    networks:
      - app-network

  mysqldb:
    image: mysql:8.0  # Use the official MySQL image
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: timetracker
      MYSQL_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
